version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region "${AWS_REGION}")
      - echo Pulling latest build for cache...
      - docker pull "${IMAGE_REPO}" || true
  build:
    commands:
      - echo Build started on `date`, building the docker image...
      - docker build --cache-from "${IMAGE_REPO}" --build-arg COMMIT="${CODEBUILD_RESOLVED_SOURCE_VERSION}" --tag "${IMAGE_REPO}" agent
  post_build:
    commands:
      - echo Build completed on `date`, pushing the Docker image...
      - docker push "${IMAGE_REPO}"
